site_name: Cider User Guide
repo_url: https://github.com/aplteam/Cider
repo_name: aplteam/Cider

docs_dir: source

nav:
  - About Cider: index.md
  - Get started: get-started.md
  - User commands: user-commands.md
  - Open project: open-project.md
  - API functions: api.md
  - Configuration: configuration.md
  - Troubleshooting: troubleshooting.md
  - Release notes: release-notes.md
  - Contributing: contributing.md

theme:
  custom_dir: overrides
  favicon: 'img/cider-logo.png'
  # logo: 'img/dyalog-white.svg'
  icon:
    logo: dyalog/cider-logo
  name: material
  font:
      text: Be Vietnam Pro
  features:
    - content.tabs.link
    - navigation.instant
    - navigation.path
    - navigation.sections
    # - navigation.tabs
    - navigation.tracking
  palette:
    primary: custom
    accent: custom

extra:
  version_maj: 0
  version_majmin: 0.44
  version:
    provider: mike


extra_css:
  - style/main.css
  - style/extra.css
  - style/admonition-ucmdhelp.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  # - privacy
  - search
  - git-revision-date
  # - macros
  # - monorepo
  # - caption:
  #     table:
  #       enable: true
  #       start_index: 1
  #       increment_index: 1
  #       position: bottom

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - markdown_tables_extended
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - toc:
      title: On this page
